# Generated by Django 3.0.6 on 2020-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200531_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('M', 'primary'), ('N', 'secondary')], default='M', max_length=1),
        ),
    ]
