# Generated by Django 3.0.6 on 2020-05-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='M', max_length=8),
        ),
    ]
