# Generated by Django 3.0.6 on 2020-06-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default='test', null=True),
        ),
    ]
