# Generated by Django 3.0.6 on 2020-06-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
