# Generated by Django 3.0.6 on 2020-06-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200625_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
    ]
