# Generated by Django 3.0.6 on 2020-06-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200625_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='name',
            new_name='username',
        ),
    ]
