# Generated by Django 3.0.6 on 2020-07-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200708_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
