# Generated by Django 3.0.6 on 2020-07-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('cart', '0006_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='MyCity',
        ),
    ]
