# Generated by Django 3.0.6 on 2020-07-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200705_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutinfo',
            options={'verbose_name_plural': 'Checkoutinfo'},
        ),
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.IntegerField(default=12000),
        ),
    ]
